/* 00 normal skill / 10 target skill / 30 buffed skill */
module.exports = [
//  {enabled: true, job: x, group:  x, replace: xxxxxx, instance: true, Description:""},
	// 0-warrior 
	{enabled: true, job: 0, group:  1, replace:  11200, instance: true, Description:"Combo Attack"},
	{enabled: true, job: 0, group:  4, replace: 40930, instance: true, Description:"Rain of Blows"},
	{enabled: false, job: 0, group: 19, replace: 191101, instance: true, Description:"Rising Fury -> last hit"},
	{enabled: true, job: 0, group: 28, replace: 390130, instance: true, Description:"Traverse Cut"},
	{enabled: true, job: 0, group: 29, replace: 290930, instance: true, Description:"Blade Draw"},
	{enabled: true, job: 0, group: 30, replace: 300930, instance: true, Description:"Scythe"},
	{enabled: true, job: 0, group: 31, replace: 310830, instance: true, Description:"Reaping Slash"},
	{enabled: true, job: 0, group: 36, replace: 360130, instance: true, Description:"Rain of Blows (Deadly Gamble)"},
	{enabled: true, job: 0, group: 37, replace: 370130, instance: true, Description:"Blade Draw (Deadly Gamble)"},
	{enabled: true, job: 0, group: 38, replace: 300930, instance: true, Description:"Scythe (Deadly Gamble)"},
	{enabled: true, job: 0, group: 39, replace: 390130, instance: true, Description:"Traverse Cut (Defensive Stance)"},
	{enabled: false, job: 0, group: 40, replace: 400122, instance: true, Description:"Blade Waltz -> auto-block"},
	{enabled: false, job: 0, group: 41, replace: 410131, instance: true, Description:"Aerial Scythe -> last hit"},
	{enabled: true, job: 0, group: 42, replace: 420130, instance: true, Description:"Blade Frenzy -> cast speed"},
	// 1-lancer 
	{enabled: true, job: 1, group:  1, replace:  11200, instance: true, Description:"Combo Attack -> Fist hit"},
	{enabled: true, job: 1, group:  3, replace:  30200, instance: true, Description:"Onslaught  -> accelerate"},
	{enabled: true, job: 1, group:  5, replace:  50130, instance: true, Description:"Shield Bash   -> accelerate"},
	{enabled: true, job: 1, group: 10, replace: 100330, instance: true, Description:"Debilitate -> Buffed"},
	{enabled: true, job: 1, group: 13, replace: 131130, instance: true, Description:"Spring Attack  -> accelerate"},
	{enabled: true, job: 1, group: 18, replace: 181101, instance: true, Description:"Shield Barrage  -> last hit no CD"},
	{enabled: true, job: 1, group: 21, replace: 210402, instance: true, Description:"Lockdown Blow  -> accelerate"},
	{enabled: true, job: 1, group: 25, replace: 251030, instance: true, Description:"Wallop       -> accelerate"},
	{enabled: true, job: 1, group: 28, replace: 280101, instance: true, Description:"Super Leap   -> accelerate"},
	// 2-slayer 
	{enabled: true, job: 2, group:  1, replace:  11200, instance: true, Description:"Combo Attack -> Fist hit"},
	{enabled: true, job: 2, group:  2, replace:  21130, instance: true, Description:"Knockdown Strike    -> accelerate"},
	{enabled: true, job: 2, group:  4, replace:  40200, instance: true, Description:"Evasive Roll  -> no CD"},
	{enabled: true, job: 2, group:  8, replace:  81030, instance: true, Description:"Overhand Strike   -> accelerate"},
	{enabled: true, job: 2, group: 12, replace: 121102, instance: true, Description:"Heart Thrust  -> accelerate"},
    {enabled: true, job: 2, group: 23, replace: 230930, instance: true, Description:"Measured Slice   -> accelerate"},
	{enabled: true, job: 2, group: 24, replace: 240930, instance: true, Description:"Eviscerate  -> accelerate"},
	{enabled: true, job: 2, group: 25, replace: 250130, instance: true, Description:"Ultimate Overhand Strike -> accelerate"},
	{enabled: true, job: 2, group: 26, replace: 260130, instance: true, Description:"Punishing Blow        -> accelerate"},
	// 3-berserker 

	// 4-sorcerer 
	{enabled: true, job: 4, group:  4, replace: 330112, instance: true, Description:"Arcane Pulse"},
	{enabled: true, job: 4, group:  6, replace: 320100, instance: true, Description:"Meteor Strike"},
	{enabled: true, job: 4, group: 34, replace: 340230, instance: true, Description:"Mana Boost"},
	{enabled: true, job: 4, group: 36, replace: 360600, instance: true, Description:"Fusion"},
	// 5-archer 

	// 6-priest 
	{enabled: true, job: 6, group:  3, replace:  30730, instance: true, Description:"Healing Circle  -> Buffed"},
	{enabled: true, job: 6, group: 11, replace: 111102, instance: true, Description:"Metamorphic Blast   -> Buffed"},
	{enabled: true, job: 6, group: 16, replace: 161121, instance: true, Description:"Shocking Implosion   -> Buffed"},
	{enabled: true, job: 6, group: 27, replace: 271121, instance: true, Description:"Final Reprisal   -> Buffed"},
	{enabled: true, job: 6, group: 40, replace: 401020, instance: true, Description:"Zenobia's Vortex    -> Buffed"},
	{enabled: true, job: 6, group: 42, replace: 420130, instance: true, Description:"Holy Burst   -> Buffed"},
	// 7-mystic 
	// {enabled: true, job: x, group:  x, replace: xxxxxx, instance: true, Description:""},

	// 8-reaper 
	{enabled: true, job: 8, group:  3, replace:  30341, instance: true, Description:"Double Shear -> Buffed"},
	{enabled: true, job: 8, group:  4, replace:  40331, instance: true, Description:"Sundering Strike"},
	{enabled: true, job: 8, group:  5, replace:  50332, instance: true, Description:"Grim Strike"},
	{enabled: true, job: 8, group:  6, replace:  60242, instance: true, Description:"Death Spiral -> second hit"},
	{enabled: true, job: 8, group:  8, replace:  80230, instance: true, Description:"Whipsaw"},
	{enabled: true, job: 8, group: 10, replace: 100230, instance: true, Description:"Pendulum Strike"},
	{enabled: true, job: 8, group: 11, replace: 110203, instance: true, Description:"Shadow Lash    -> instante charge no CD"},
	{enabled: true, job: 8, group: 12, replace: 120231, instance: true, Description:"Shadow Burst"},
	{enabled: true, job: 8, group: 15, replace: 150380, instance: true, Description:"Retribution     -> second hit Buffed"},
	{enabled: true, job: 8, group: 40, replace: 400100, instance: true, Description:"Shadow Step   -> Fist hit no CD"},
	// 9-gunner 
	{enabled: true, job: 9, group:  1, replace: 420101, instance: true, Description:"Blast"},
	{enabled: true, job: 9, group:  5, replace:  51021,    combo: true, Description:"Burst Fire"},
	{enabled: true, job: 9, group:  9, replace:  93112, instance: true,Description:"Mana Missiles"},
	{enabled: true, job: 9, group: 11, replace: 110831, instance: true, Description:"Rocket Jump   -> 2 steps buff"},
	{enabled: true, job: 9, group: 13, replace: 440101, instance: true,Description:"Balder's Vengeance"},
	{enabled: true, job: 9, group: 40, replace: 400102, instance: true, Description:"Rolling Reload / Dashing Reload"},
	{enabled: true, job: 9, group: 43, replace: 430151, instance: true, Description:"Remote Trigger"},
	// 10-brawler 
	{enabled: true, job:10, group:  1, replace:  21201, instance: true, Description:"Punch -> Fist hit"},
	{enabled: true, job:10, group:  4, replace:  41130, instance: true, Description:"Ground Pound"},
	{enabled: true, job:10, group: 22, replace: 220130, instance: true, Description:"Flying Kick"},
	{enabled: true, job:10, group: 24, replace: 240130, instance: true, Description:"(One-Inch) Punch   -> 2 stage acceleration"},
	{enabled: true, job:10, group: 26, replace: 260102, instance: true, Description:"Rhythmic Blows"},
	{enabled: true, job:10, group: 40, replace: 400100, instance: true, Description:"Quick Dash"},
	// 11-ninja 
	{enabled: true, job:11, group:  1, replace: 150732, instance: true, Description:"Combo Attack -> Fist hit", autoRepeat: false},
	{enabled: true, job:11, group:  2, replace:  20100, instance: true, Description:"Shadow Jump -> Fist hit"},
	{enabled: true, job:11, group:  3, replace:  30840, instance: true, Description:"Leaves on the Wind"},
	{enabled: true, job:11, group:  8, replace:  80252, instance: true, Description:"Fire Avalanche"},
	{enabled: true, job:11, group: 21, replace: 210112, instance: true, Description:"Boomerang Shuriken"},
	{enabled: true, job:11, group: 22, replace: 220140, instance: true, Description:"Quick Attack"},
	// 12-valkyrie 
	{enabled: true, job:12, group: 1, replace: 10103, instance: true, Description:"Slash Last hit", autoRepeat: false},
	{enabled: true, job:12, group: 2, replace: 25730, instance: true, Description:"Overhead Slash buffed"},
	{enabled: true, job:12, group: 3, replace: 35930, instance: true, Description:"Glaive Strike buffed"},
	{enabled: true, job:12, group: 5, replace: 55530, instance: true, Description:"Maelstrom buffed"},
	{enabled: true, job:12, group: 6, replace: 66230, instance: true, Description:"Leaping Slash buffed"},
	{enabled: true, job:12, group: 7, replace: 70902, instance: true, Description:"Leaping Strike last hit"},
	{enabled: true, job:12, group: 8, replace: 85101, instance: true, Description:"Titansbane"},
	{enabled: true, job:12, group: 9, replace: 96130, instance: true, Description:"Ground Bash Buffed"},
	{enabled: true, job:12, group: 10, replace: 106130, instance: true, Description:"Dream Slash buffed"},
	{enabled: true, job:12, group: 13, replace: 136130, instance: true, Description:"Bloodflower buffed"},
	{enabled: true, job:12, group: 14, replace: 140100, instance: true, Description:"Evasion no CD"},
	{enabled: true, job:12, group: 15, replace: 156130, instance: true, Description:"Windslash buffed"},
	{enabled: true, job:12, group: 16, replace: 166230, instance: true, Description:"Runeburst"},
	{enabled: true, job:12, group: 21, replace: 215100, instance: true, Description:"Dark Herald Buffed"},
	{enabled: true, job:12, group: 23, replace: 235102, instance: true, Description:"Gungnir’s Bite - Fist hit"},
	{enabled: false, job:12, group: 24, replace: 245102, instance: true, Description:"Twilight Waltz -> Fist hit"},
	{enabled: false, job:12, group: 25, replace: 250132, instance: true, Description:"Godsfall -> Fist hit"}
]
